### PR TITLE
Add translation for Spanish (Argentina)

### PR DESCRIPTION
**Pull request by megatux**
Initial version. This is for Spanish, Argentina. There are small differences in terminology with Spain.
I tried to build (meson+ninja) & install but I'm unable to see the UI in Spanish. Is anything else needed? I want to give it a good overall navigation to validate this messages.

### CODE REVIEW

**Comment by amka** [comment]
@megatux I do my development inside Builder and it runs with my locale out of the box. According to app logic, your changes should work as well.

**Comment by megatux** [comment]
Oh, ok. Interesting. Will give it a try there. Thanks

**Comment by amka** [comment]
One more thing, probably you'll have to set env var LANGUAGE to es_AR. Hope it helps. Thank you for using and helping :)

**Comment by megatux** [comment]
yeah, that env. var is already set. I'm seeng this msg when starting:

> GETTEXT:  /usr/share/locale com.github.tenderowl.norka None

maybe is an installation issue. Where are the .po files installed?

**Comment by amka** [comment]
Hm, maybe a bug. Will investigate it today.

**Pull request merged**
